<!DOCTYPE html>
<html lang="ar">
<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <title><?php echo $pageTitle ?? "نظام الانتخابات"; ?></title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.rtl.min.css" rel="stylesheet">
          <!-- تضمين Font Awesome -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-yH4pEeI2/4f0b6o28JJoZt4xFJQp7jicnT3vM+gHZ6pDymohH3ucYBS8n1ObhZ5rN3Qqn2O2YjjlMYCUMByKpg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
              <style>
                  body {
                        background-color: #f9fafb;
                              direction: rtl;
                                  }
                                      .navbar {
                                            background: linear-gradient(45deg, #0d6efd, #6610f2);
                                                }
                                                    .navbar-brand, .nav-link {
                                                          color: #fff !important;
                                                                font-weight: bold;
                                                                    }
                                                                        .nav-link i {
                                                                              margin-left: 5px;
                                                                                  }
                                                                                      .hero {
                                                                                            background: linear-gradient(135deg, #0d6efd, #6610f2);
                                                                                                  color: #fff;
                                                                                                        padding: 60px 15px;
                                                                                                              text-align: center;
                                                                                                                  }
                                                                                                                      .hero h1 {
                                                                                                                            font-size: 2.5rem;
                                                                                                                                  margin-bottom: 15px;
                                                                                                                                      }
                                                                                                                                          .hero p {
                                                                                                                                                font-size: 1.1rem;
                                                                                                                                                    }
                                                                                                                                                        .btn-custom {
                                                                                                                                                              border-radius: 50px;
                                                                                                                                                                    padding: 10px 20px;
                                                                                                                                                                          margin: 5px;
                                                                                                                                                                                font-size: 1rem;
                                                                                                                                                                                    }
                                                                                                                                                                                        .footer {
                                                                                                                                                                                              background: #6610f2;
                                                                                                                                                                                                    color: #fff;
                                                                                                                                                                                                          text-align: center;
                                                                                                                                                                                                                padding: 15px 0;
                                                                                                                                                                                                                      margin-top: 30px;
                                                                                                                                                                                                                          }
                                                                                                                                                                                                                            </style>
                                                                                                                                                                                                                            </head>
                                                                                                                                                                                                                            <body>
                                                                                                                                                                                                                              <nav class="navbar navbar-expand-lg">
                                                                                                                                                                                                                                  <div class="container">
                                                                                                                                                                                                                                        <a class="navbar-brand" href="index.php">
                                                                                                                                                                                                                                                <i class="fa-solid fa-vote-yea"></i> انتخابات
                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                                                                                                                                                                                                                                                                          aria-controls="navbarNav" aria-expanded="false" aria-label="تبديل التنقل">
                                                                                                                                                                                                                                                                                  <span class="navbar-toggler-icon"></span>
                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                              <div class="collapse navbar-collapse" id="navbarNav">
                                                                                                                                                                                                                                                                                                      <ul class="navbar-nav ms-auto">
                                                                                                                                                                                                                                                                                                                <?php if (isset($_SESSION['admin_logged_in']) && $_SESSION['admin_logged_in'] === true): ?>
                                                                                                                                                                                                                                                                                                                            <li class="nav-item">
                                                                                                                                                                                                                                                                                                                                          <a class="nav-link" href="admin_tools.php">
                                                                                                                                                                                                                                                                                                                                                          الأدمن <i class="fa-solid fa-user-shield"></i>
                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                        <li class="nav-item">
                                                                                                                                                                                                                                                                                                                                                                                                                    <a class="nav-link" href="add_votes.php">
                                                                                                                                                                                                                                                                                                                                                                                                                                  إدخال الأصوات <i class="fa-solid fa-edit"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <li class="nav-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a class="nav-link" href="logout.php">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            تسجيل الخروج <i class="fa-solid fa-sign-out-alt"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="container my-4">