<?php
session_start();
require 'config.php';
header('Content-Type: application/json');

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $center_id   = (int) $_POST['center_id'];
        $station_id  = (int) $_POST['station_id'];
            $candidate_id = (int) $_POST['candidate_id'];
                
                    // نفحص قيمة حقل الأصوات بشكل دقيق:
                        // إذا كان الحقل موجوداً ولكن قيمته فارغة (أي "") فإننا نقوم بحذف السجل إن وجد
                            if (isset($_POST['vote_count']) && $_POST['vote_count'] === "") {
                                    // محاولة حذف السجل (إن وُجد)
                                            $stmt = $pdo->prepare("DELETE FROM votes WHERE center_id = :center_id AND station_id = :station_id AND candidate_id = :candidate_id");
                                                    $stmt->execute([
                                                                'center_id'    => $center_id,
                                                                            'station_id'   => $station_id,
                                                                                        'candidate_id' => $candidate_id
                                                                                                ]);
                                                                                                        
                                                                                                                // تسجيل العملية في السجل
                                                                                                                        $date = date("Y-m-d H:i:s");
                                                                                                                                if(isset($_SESSION['username'])){
                                                                                                                                            $stmtUser = $pdo->prepare("SELECT fullname FROM users WHERE username = ?");
                                                                                                                                                        $stmtUser->execute([$_SESSION['username']]);
                                                                                                                                                                    $user = $stmtUser->fetch();
                                                                                                                                                                                $user_fullname = $user ? $user['fullname'] : $_SESSION['username'];
                                                                                                                                                                                        } else {
                                                                                                                                                                                                    $user_fullname = "admin";
                                                                                                                                                                                                            }
                                                                                                                                                                                                                    $stmtCenter = $pdo->prepare("SELECT center_name FROM centers WHERE id = ?");
                                                                                                                                                                                                                            $stmtCenter->execute([$center_id]);
                                                                                                                                                                                                                                    $center_name = $stmtCenter->fetchColumn();
                                                                                                                                                                                                                                            $stmtStation = $pdo->prepare("SELECT station_number FROM stations WHERE id = ?");
                                                                                                                                                                                                                                                    $stmtStation->execute([$station_id]);
                                                                                                                                                                                                                                                            $station_number = $stmtStation->fetchColumn();
                                                                                                                                                                                                                                                                    $stmtCandidate = $pdo->prepare("SELECT candidate_name FROM candidates WHERE id = ?");
                                                                                                                                                                                                                                                                            $stmtCandidate->execute([$candidate_id]);
                                                                                                                                                                                                                                                                                    $candidate_name = $stmtCandidate->fetchColumn();
                                                                                                                                                                                                                                                                                            $log_message = "$date - $user_fullname حذف الأصوات من المركز $center_name في المحطة $station_number للمرشح $candidate_name\n";
                                                                                                                                                                                                                                                                                                    file_put_contents('logs.txt', $log_message, FILE_APPEND);
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    echo json_encode(['status' => 'success', 'message' => 'تم حذف الأصوات']);
                                                                                                                                                                                                                                                                                                                            exit;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        // في حال كانت قيمة الحقل غير فارغة (حتى وإن كانت "0")
                                                                                                                                                                                                                                                                                                                                            // نحول القيمة إلى عدد صحيح
                                                                                                                                                                                                                                                                                                                                                $vote_count = (int)$_POST['vote_count'];
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                        if ($center_id && $station_id && $candidate_id) {
                                                                                                                                                                                                                                                                                                                                                                // استرجاع اسم المستخدم الكامل
                                                                                                                                                                                                                                                                                                                                                                        if(isset($_SESSION['username'])){
                                                                                                                                                                                                                                                                                                                                                                                    $stmtUser = $pdo->prepare("SELECT fullname FROM users WHERE username = ?");
                                                                                                                                                                                                                                                                                                                                                                                                $stmtUser->execute([$_SESSION['username']]);
                                                                                                                                                                                                                                                                                                                                                                                                            $user = $stmtUser->fetch();
                                                                                                                                                                                                                                                                                                                                                                                                                        $user_fullname = $user ? $user['fullname'] : $_SESSION['username'];
                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                            $user_fullname = "admin";
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            // استرجاع اسم المركز
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmtCenter = $pdo->prepare("SELECT center_name FROM centers WHERE id = ?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmtCenter->execute([$center_id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $center_name = $stmtCenter->fetchColumn();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // استرجاع رقم المحطة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmtStation = $pdo->prepare("SELECT station_number FROM stations WHERE id = ?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmtStation->execute([$station_id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $station_number = $stmtStation->fetchColumn();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // استرجاع اسم المرشح
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmtCandidate = $pdo->prepare("SELECT candidate_name FROM candidates WHERE id = ?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmtCandidate->execute([$candidate_id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $candidate_name = $stmtCandidate->fetchColumn();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // التحقق من وجود سجل الأصوات الحالي
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt = $pdo->prepare("SELECT id FROM votes WHERE center_id = :center_id AND station_id = :station_id AND candidate_id = :candidate_id");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt->execute([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'center_id'    => $center_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'station_id'   => $station_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'candidate_id' => $candidate_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($stmt->rowCount() > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // تحديث السجل الحالي حتى وإن كانت القيمة 0 (وهنا تعتبر "0" صوتاً مدخلاً)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $update = $pdo->prepare("UPDATE votes SET vote_count = :vote_count WHERE center_id = :center_id AND station_id = :station_id AND candidate_id = :candidate_id");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $update->execute([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'vote_count'   => $vote_count,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'center_id'    => $center_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'station_id'   => $station_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'candidate_id' => $candidate_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // إدراج سجل جديد حتى وإن كانت القيمة 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $insert = $pdo->prepare("INSERT INTO votes (candidate_id, center_id, station_id, vote_count) VALUES (:candidate_id, :center_id, :station_id, :vote_count)");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $insert->execute([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'candidate_id' => $candidate_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'center_id'    => $center_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'station_id'   => $station_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'vote_count'   => $vote_count
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // تسجيل النشاط في السجل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $date = date("Y-m-d H:i:s");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $log_message = "$date - $user_fullname أضاف $vote_count صوت في المركز $center_name في المحطة $station_number إلى المرشح $candidate_name\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                file_put_contents('logs.txt', $log_message, FILE_APPEND);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo json_encode(['status' => 'success', 'message' => 'تم حفظ الأصوات']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo json_encode(['status' => 'error', 'message' => 'يرجى ملء جميع الحقول بشكل صحيح.']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo json_encode(['status' => 'error', 'message' => 'طريقة الطلب غير صحيحة.']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?>